apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: stream
      labels:
        app: stream
    spec:
      containers:
      - name: stream
        image: docker.io/tyacbovi/sourcestream
        env:
        - name: KAFKA_ADDRESS
          value: kafka.kafka:9092
        - name: SCHEMA_REGISTRY_ADDRESS
          value: http://schema-registry.kafka:8081
	- name: SOURCE_NAME
	  value: source1
