apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marine-stream
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: marine-stream
      labels:
        app: marine-stream
    spec:
      containers:
      - name: marine-stream
        image: docker.io/tyacbovi/sourcestream
        env:
        - name: KAFKA_ADDRESS
          value: kafka.kafka:9092
        - name: SCHEMA_REGISTRY_IP
          value: http://schema-registry.kafka:8081
        - name: SOURCE_NAME
          value: marine_traffic
