/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.sourcestream.entities;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum category {
  airplane, boat  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"category\",\"namespace\":\"org.sourcestream.entities\",\"symbols\":[\"airplane\",\"boat\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
