/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.sourcestream.entities;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum nationality {
  ISRAEL, USA, SPAIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"nationality\",\"namespace\":\"org.sourcestream.entities\",\"symbols\":[\"ISRAEL\",\"USA\",\"SPAIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
